language: java
jdk:
  - openjdk15
before_install:
  - cd spring
  - chmod +x gradlew
script:
  - ./gradlew assemble
  - ./gradlew test
after_success:
  - echo "token" > .cc_token
  - bash <(curl -s https://codecov.io/bash) -t @.cc_token